apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-secure-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-secure-api
  template:
    metadata:
      labels:
        app: go-secure-api
    spec:
      containers:
      - name: go-secure-api
        image: go-secure-api:latest 
        imagePullPolicy: IfNotPresent # prevents k8s from pulling the image from a registry
        ports:
        - containerPort: 8080
