apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: go-secure-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-secure-api
  minReplicas: 1          # Minimum number of pods
  maxReplicas: 10         # Maximum number of pods
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Scale when CPU utilization exceeds 50%
